#!/usr/bin/env bash
# This script configures the Nginx server so that
# /redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get -y install nginx
sudo touch /var/www/html/index.html
sudo chown -R "$USER":"$USER" /var/www
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
newlines="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "/server {/a $location_block" /etc/nginx/sites-available/default
sudo service nginx restart
