#!/usr/bin/env bash
# This script configures the Nginx server so that
# /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo touch /var/www/html/index.html
sudo chown -R "$USER":"$USER" /var/www
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

location_regex='^[[:space:]]*location[[:space:]]+/[[:alnum:]_/]*redirect_me[[:alnum:]_/]*[[:space:]]*{[[:space:]]*$'
if sudo grep -q -E "$location_regex" /etc/nginx/sites-available/default; then
    echo "Redirect rule already exists."
else
    redirect_config='	if ($request_filename ~ redirect_me) {\n\t\trewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}'
    sudo sed -i "/^\s*server\s*{$/a $redirect_config" /etc/nginx/sites-available/default
    echo "Redirect rule added."
fi

service nginx restart
