#!/usr/bin/env bash
# 404 Not Found Page

apt-get update
apt-get install -y nginx

touch /var/www/whytecode.tech/html/index.html /var/www/whytecode.tech/html/404.html
echo "Hello World!" > /var/www/whytecode.tech/html/index.html
echo "Ceci n'est pas une page" > /var/www/whytecode.tech/html/404.html

sed -i "s|# server {|server {\n    listen		80 default_server;\n    listen		[::]:80 default_server;\n\n    root		/var/www/whytecode.tech/html;\n    index		index.html index.htm index.nginx-debian.html;\n\n    error_page 404 /404.html;\n    location = /404.html {\n        internal;\n    }\n}|" /etc/nginx/sites-available/default

service nginx restart
