#!/usr/bin/env bash
# 404 Not Found Page

apt-get update
apt-get install -y nginx

touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html/;
    index  index.html index.htm;

}" > /etc/nginx/sites-available/default

service nginx restart
